const suggestions = [
    "Ayam Betutu",
    "Gogos",
    "Gudeg",
    "Halua Kenari",
    "Hekeng",
    "Ikan Bakar Manokwari",
    "Kerak Telor",
    "Nasi Sela Bali",
    "Nasi Uduk",
    "Pallubasa",
    "Papeda",
    "Pempek",
    "Pengkang",
    "Rendang",
    "Sate Lilit",
    "Sate Padang",
    "Soto Banjar",
    "Udang Selingkuh",
]